### ISSUE TITLE
Explore removing all the subsequent MaterialApps in order to improve Focus support

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#503]
I think we may not need the extra MaterialApps and this will simplify focus support

## Acceptance Criteria
* See if it is possible to remove the `MaterialApp` from shrine, rally, crane, starter, and demo screens

**Comment by perclasson** [comment]
After replacing MaterialApp with a Navigator wrapped in Theme in the study Rally, we are still not able to simplify the focus support. I think it is because it is the Navigator has a separate FocusScope:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/navigator.dart#L2338

I'll investigate a bit more to see if it's possible to get around the Navigator problem for the studies and if not just look at removing MaterialApp from the demo screens.

**Comment by perclasson** [comment]
It seems as if we can remove the MaterialApp from the demos though. I'll create a PR for this.

Cc @JoseAlba  this might simplify the Focus work for the demo screen
